### ISSUE TITLE
statusService.pushByUids() 传入records参数的时候,不应该判断这个参数是否为空数组吗

### ISSUE THREAD

**Issue by gitig** [NetEase/pomelo-status-plugin#4]
https://github.com/NetEase/pomelo-status-plugin/blob/master/lib/service/statusService.js#L101

RT:如果这个数组为空 就不用调用channelService.pushMessageByUids()

```
if(records.length === 0) {
  utils.invokeCallback(cb)
  return;
}
channelService.pushMessageByUids(route, msg, records, cb);
```

这样所有的uids都不在线的话 就不用发了

**Comment by py8765** [comment]
因为当时考虑到channelService里面已经做过判断了，所以status组件里就没有必要再去判断一次。
